### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toCSS' of undefined

### ISSUE THREAD

**Issue by YurySolovyov** [abe33/atom-pigments#108]
[Enter steps to reproduce below:]
1. try to open some minified js file
2. error happens

**Atom Version**: 1.1.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.18.1
### Stack Trace

Uncaught TypeError: Cannot read property 'toCSS' of undefined

```
At C:\Users\Yury\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:770

TypeError: Cannot read property 'toCSS' of undefined
    at DotRenderer.module.exports.DotRenderer.render (C:\Users\Yury\.atom\packages\pigments\lib\renderers\dot.coffee:28:41)
    at pigments-color-marker.ColorMarkerElement.render (C:\Users\Yury\.atom\packages\pigments\lib\color-marker-element.coffee:48:46)
    at pigments-color-marker.ColorMarkerElement.checkScreenRange (C:\Users\Yury\.atom\packages\pigments\lib\color-marker-element.coffee:66:8)
    at C:\Users\Yury\.atom\packages\pigments\lib\color-buffer-element.coffee:59:16
    at Array.forEach (native)
    at C:\Users\Yury\.atom\packages\pigments\lib\color-buffer-element.coffee:57:20
    at Emitter.module.exports.Emitter.emit (C:\Users\Yury\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\Yury\AppData\Local\atom\app-1.1.0\resources\app.asar\src\text-editor.js:181:32
    at Emitter.module.exports.Emitter.emit (C:\Users\Yury\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (C:\Users\Yury\AppData\Local\atom\app-1.1.0\resources\app.asar\src\display-buffer.js:297:20)
```
### Commands

```
     -8:23.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -8:23.3.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -8:22.3.0 core:undo (atom-text-editor.editor.is-focused)
     -8:18.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -8:17.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -8:17.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:17.1.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -8:13.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:09.5.0 core:save (atom-text-editor.editor.is-focused)
     -8:01.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -8:00.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -7:59.7.0 core:select-down (atom-text-editor.editor.is-focused)
     -7:59.6.0 core:delete (atom-text-editor.editor.is-focused)
     -7:59.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:03.3.0 core:paste (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "pigments": {
    "markerType": "dot"
  }
}
```
### Installed Packages

``` coffee
# User
highlight-selected, v0.10.1
minimap, v4.15.2
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
pigments, v0.18.1
Stylus, v1.2.1
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @YuriSolovyov, thanks for the report, I'm not really sure why you got this but I'll add a guard to prevent this kind of errors in the future.

**Comment by YuriSolovyov** [comment]
Thanks, @abe33, I will test as soon as new version will be out there.

**Comment by geebru** [comment]
Strangely enough I'm seeing this issue now when I highlight a large block of text and try to delete it.

See quick gif here - http://cl.ly/390l1b3R0935

Seems to only occur on larger blocks (and seemingly randomly). I can't accurately reproduce this but figured I would throw a comment here to see if I'm doing something weird.

**Comment by YuriSolovyov** [comment]
I must say I didn't seen this for long, but I was able to reproduce it by:
- repeating jQuery source several times
- saving .js file
- closing editor
- opening file
- deleting whole content or bug chunk in the middle.

Might require some additional steps, but in general works like so.

**Comment by nunocastromartins** [comment]
I can confirm. I keep getting this error when deleting large blocks of CSS. Had to disable the package as it was becoming quite annoying.

**Comment by molovo** [comment]
I'm also receiving this is SASS files (indented-syntax only). Highlight a block of text, and one of either backspace, delete or ctrl+x will cause the error. It's very random, sometimes backspace doesn't work, so I have to hit delete, sometimes vice-versa.

**Comment by davidbarker** [comment]
I just received this error when attempting to delete ~50 lines from a .scss file.

**Comment by pitops** [comment]
this error still exists when trying to use control-x to cut some javascript code which has css control

**Comment by Jojokats** [comment]
I also got this error today so there is still an issue.

**Comment by abe33** [comment]
@Jojokats, @pitops Hmm, are you sure the stack trace is the same? Just wondering if it could come from another part of Pigments.

**Comment by himynameisdave** [comment]
:+1: this is annoying af

**Comment by himynameisdave** [comment]
Updating to `0.23.1` solves the issue thanks.

**Comment by pitops** [comment]
yes problem seems resolved now.

**Comment by sashamorozov** [comment]
`0.23.1` doesn't solve the issue. If I try to remove a lot of text in `scss` i got this error.

![image](https://cloud.githubusercontent.com/assets/4144548/12981009/f7fc54b4-d0ef-11e5-92f0-1bcfdb2a3b53.png)

**Comment by himynameisdave** [comment]
@sashamorozov try and close then re-open Atom and it should be good. Maybe not but it's how I got mine working after bumping to `0.23.1`

**Comment by davidbarker** [comment]
I appear to still have this error while running `0.23.1`.

**Comment by sashamorozov** [comment]
@himynameisdave I always close Atom after work, but this doesn't work :(
I disable the plugin to remove the text, and then turn on. It is very strange.

**Comment by abe33** [comment]
For those who still get the issue, could you post the stack trace you get, I want to confirm if it comes from the same parts in my the code.

**Comment by sashamorozov** [comment]
@abe33 Hi,

```
TypeError: Cannot read property 'toCSS' of undefined
    at DotRenderer.module.exports.DotRenderer.render (/Users/user/.atom/packages/pigments/lib/renderers/dot.coffee:28:41)
    at pigments-color-marker.ColorMarkerElement.render (/Users/user/.atom/packages/pigments/lib/color-marker-element.coffee:63:46)
    at pigments-color-marker.ColorMarkerElement.checkScreenRange (/Users/user/.atom/packages/pigments/lib/color-marker-element.coffee:84:8)
    at /Users/user/.atom/packages/pigments/lib/color-buffer-element.coffee:56:16
    at Array.forEach (native)
    at /Users/user/.atom/packages/pigments/lib/color-buffer-element.coffee:54:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:219:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:313:20)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1227:19)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1189:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:412:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:74:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:671:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:572:12)
    at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:675:19)
    at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:600:37)
    at Selection.module.exports.Selection.backspace (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:515:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:828:26
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:844:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1244:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:838:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2124:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2086:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:836:19)
    at TextEditor.module.exports.TextEditor.backspace (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:827:19)
    at TextEditor.object.(anonymous function) [as backspace] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
```

**Comment by abe33** [comment]
@sashamorozov Thank you! It looks the color is removed between the check in the color marker element and the call to render. I'll add a guard in the renderer's method to catch that before accessing the marker's color.

**Comment by himynameisdave** [comment]
Oh ya still getting this issue, dafuq?

####Le stack trace
```
TypeError: Cannot read property 'toCSS' of undefined
    at DotRenderer.module.exports.DotRenderer.render (/Users/dlunny/.atom/packages/pigments/lib/renderers/dot.coffee:28:41)
    at pigments-color-marker.ColorMarkerElement.render (/Users/dlunny/.atom/packages/pigments/lib/color-marker-element.coffee:63:46)
    at pigments-color-marker.ColorMarkerElement.checkScreenRange (/Users/dlunny/.atom/packages/pigments/lib/color-marker-element.coffee:84:8)
    at /Users/dlunny/.atom/packages/pigments/lib/color-buffer-element.coffee:56:16
    at Array.forEach (native)
    at /Users/dlunny/.atom/packages/pigments/lib/color-buffer-element.coffee:54:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:219:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:313:20)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1227:19)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1189:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:412:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:74:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:671:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:572:12)
    at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:675:19)
    at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:600:37)
    at Selection.module.exports.Selection.delete (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:557:19)
    at Selection.module.exports.Selection.cut (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:723:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2506:21
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:844:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
```

**Comment by himynameisdave** [comment]
Status plz? Using [this package instead](https://github.com/abe33/atom-color-highlight) until this gets resolved...

**Comment by abe33** [comment]
@himynameisdave You probably don't run the latest version, line 28 of the latest version is https://github.com/abe33/atom-pigments/blob/master/lib/renderers/dot.coffee#L28
Which means you are probably running the version before, when the test on line 26 wasn't there.

As for atom-color-highlight, it's no longer maintained, and was replaced by Pigments, the README is quite clear about that.

**Comment by himynameisdave** [comment]
@abe33 thanks man I'll go update now :smile:

**Comment by davidbarker** [comment]
I'm running v0.24.1, but am still getting these errors. Here's a stack trace.

```
TypeError: Cannot read property 'toCSS' of undefined
    at SquareDotRenderer.module.exports.DotRenderer.render (/Users/davidbarker/.atom/packages/pigments/lib/renderers/dot.coffee:28:5)
    at SquareDotRenderer.module.exports.SquareDotRenderer.render (/Users/davidbarker/.atom/packages/pigments/lib/renderers/square-dot.coffee:6:18)
    at pigments-color-marker.ColorMarkerElement.render (/Users/davidbarker/.atom/packages/pigments/lib/color-marker-element.coffee:63:46)
    at pigments-color-marker.ColorMarkerElement.checkScreenRange (/Users/davidbarker/.atom/packages/pigments/lib/color-marker-element.coffee:84:8)
    at /Users/davidbarker/.atom/packages/pigments/lib/color-buffer-element.coffee:56:16
    at Array.forEach (native)
    at /Users/davidbarker/.atom/packages/pigments/lib/color-buffer-element.coffee:54:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:219:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:313:20)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1227:19)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1189:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:412:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:74:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:671:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:572:12)
    at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:675:19)
    at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:600:37)
    at Selection.module.exports.Selection.backspace (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:515:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:828:26
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:844:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1244:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:838:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2124:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2086:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:836:19)
    at TextEditor.module.exports.TextEditor.backspace (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:827:19)
    at TextEditor.object.(anonymous function) [as backspace] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditor.commandRegistry.add.stopEventPropagationAndGroupUndo.core:backspace (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:341:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:576:34
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1244:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:575:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by abe33** [comment]
I refactored all the renderers to make sure to only use a local copy of the color instead of trying to access it through the marker (with the risk the marker gets modified in the interval), I'll :ship: the patch soon.

**Comment by sashamorozov** [comment]
If it helps, I got this error when trying to remove 2+ inline svg.

**Comment by C-Bouthoorn** [comment]
Closing due to inactivity for over a year.
