### ISSUE TITLE
It does not work pigments

### ISSUE THREAD

**Issue by ray-zard** [abe33/atom-pigments#227]
After installation, without any signs of life...

`{
  "atom": "1.10.2",
  "pigments": "0.35.0",
  "platform": "win32",
  "config": {
    "traverseIntoSymlinkDirectories": false,
    "sourceNames": [
      "**/*.css",
      "**/*.styl",
      "**/*.stylus",
      "**/*.less",
      "**/*.sass",
      "**/*.scss"
    ],
    "ignoredNames": [
      "vendor/*",
      "node_modules/*",
      "spec/*",
      "test/*"
    ],
    "ignoredBufferNames": [],
    "extendedSearchNames": [
      "**/*.css"
    ],
    "supportedFiletypes": [
      "*"
    ],
    "filetypesForColorWords": [
      "css",
      "less",
      "styl",
      "stylus",
      "sass",
      "scss"
    ],
    "ignoredScopes": [],
    "autocompleteScopes": [
      ".source.css",
      ".source.css.less",
      ".source.sass",
      ".source.css.scss",
      ".source.stylus"
    ],
    "extendAutocompleteToVariables": false,
    "extendAutocompleteToColorValue": false,
    "autocompleteSuggestionsFromValue": false,
    "markerType": "background",
    "sassShadeAndTintImplementation": "compass",
    "sortPaletteColors": "none",
    "groupPaletteColors": "none",
    "mergeColorDuplicates": false,
    "delayBeforeScan": 500,
    "ignoreVcsIgnoredPaths": true
  },
  "project": {
    "config": {},
    "variables": {
      "colors": 0,
      "total": 0
    }
  }
}`

**Comment by Pavlina1979** [comment]
Same for me, after upgrade to pigments 0.35.0.
Atom 1.10.2 on Linux Mint 18 XFCE x64Bit

**Comment by RodideBoer** [comment]
I haven't seen it working. Just started using it though. pigments 0.35.1
Atom 1.10.2 on Mac OS X 10.11.6

Pigments: Find colors does find the color I have in a test file. But in the test file it will not highlight.

**Comment by erwinactionplanner** [comment]
I believe I just experienced the same issue. To outline the steps:

1. Open a CSS file in Atom (w/o Pigments installed)
2. Install Pigments
3. Note that the CSS file has no color information displayed

Tried reloading Pigments, restarting Atom: no success. Closing and reopening the CSS file did the trick, as with OP.

**Comment by TonySpegel** [comment]
@erwinactionplanner is correct. 
I am on Atom 1.10.2 and pigments 0.35.3 (windows / ubuntu)

**Comment by abe33** [comment]
Hi there, I may have missed one scenario, I'm not sure how I can simulate this post-install scenario but I'll see what I can do.

**Comment by ray-zard** [comment]
The problem was solved only by installing a different version of Windows....

**Comment by scfkcf** [comment]
I may meet the same problem.

Atom 1.11.2 on Mac OS X 10.11.6 with pigments 0.38.0

**Comment by ismailuddin** [comment]
So any solution on the horizon? Can't get it to work either after the recent update, plus the gutter name issue still persists whose respective thread is closed.

**Comment by JosephBywater** [comment]
I too, have the same problem, Mac OS 10.12.1.

**Comment by C-Bouthoorn** [comment]
Pigments is currently (afaik) only called when a file is opened, so this case is not included. @abe33 What about a one-time post-install check of open files?
